### ISSUE TITLE
fragile stdin handling

### ISSUE THREAD

**Issue by adl** [mklokocka/seminator#2]
When I was working on `autcross` this summer, and testing it on `seminator`, I ran accross a very puzzling situation.  I command like

```sh
randaut -n10 ... | autcross 'seminator %H>%O'
```
would fails with `autcross` complaining it could not read the 7th or 8th automaton produced by `randaut` because it was incompletely terminated.

I finally realized that seminator, despite being supplied a filename on the command line, was actually reading all of its stdin before simply ignoring it (silently).  As `autcross` had spawned `seminator`, the latter inherited from the stdin of the former, and was actually flushing everything in the pipe that `autcross` had not yet read.   I have fixed this in `autcross` and now it runs third-party tools with a closed stdin to protect its input.

But I still believe `seminator` should be fixed.  Reading stdin until it stop seems wrong, because stdin might never stop.  Reading stdin and silently discarding it seems wrong also.

I think you could get rid of the stdin read loop by just passing `"-"` as the filename to read to `parse_aut()` when you want to read from stdin.  Then `parse_aut()` will only read one automaton.  To display a help message, you could assume that no input is available if no filename was given and if stdin is a TTY.  That's how we check empty input in most of Spot's tools.

**Comment by xblahoud** [comment]
The "-" solution seems not to work.

**Comment by xblahoud** [comment]
When running
`ltl2tgba "FGa" | ./seminator` I get: `1.1: no automaton read (empty input?)`

**Comment by adl** [comment]
Works for me.  The fact that you get "empty input" and not "File does not exist" means it's really attempting to read stdin.  Did you forget to remove the loop at the begin of `main()` that slurps the entire input?

```patch
--- seminator.cpp.orig  2019-04-16 16:02:04.385272268 +0200
+++ seminator.cpp       2019-04-16 16:06:01.303910776 +0200
@@ -108,20 +108,6 @@
 int main(int argc, char* argv[])
 {
     // Setting up the configurations flags for the user.
-
-    std::string automata_from_cin;
-    if (!isatty(fileno(stdin)))
-    {
-        // don't skip the whitespace while reading
-        std::cin >> std::noskipws;
-
-        // use stream iterators to copy the stream to a string
-        std::istream_iterator<char> it(std::cin);
-        std::istream_iterator<char> end;
-        std::string result(it, end);
-        automata_from_cin.append(result);
-    }
-
     bool deterministic_first_component = false;
     bool optimize = true;
     bool cy_alg = false;
@@ -244,7 +230,7 @@
         }
     }
 
-    if (automata_from_cin.empty() && path_to_file.empty())
+    if (path_to_file.empty() && isatty(STDIN_FILENO))
     {
         std::cerr << "Seminator: No automaton to process?  Run 'seminator --help' for help." << std::endl;
         return 1;
@@ -254,16 +240,9 @@
 
     spot::parsed_aut_ptr parsed_aut;
 
-    if (!path_to_file.empty())
-    {
-        parsed_aut = parse_aut(path_to_file, dict);
-    }
-    else
-    {
-        const std::string filename = "Reading from std::cin pipe";
-        spot::automaton_stream_parser parser(automata_from_cin.c_str(), filename);
-        parsed_aut = parser.parse(dict);
-    }
+    if (path_to_file.empty())
+      path_to_file = "-";
+    parsed_aut = parse_aut(path_to_file, dict);
 
     if (!parsed_aut->errors.empty() || parsed_aut->aborted)
     {
```

**Comment by xblahoud** [comment]
Yes, that was it.
