### ISSUE TITLE
Remove accepting inherently terminal and deterministic bottom SCC from 1st component

### ISSUE THREAD

**Issue by xblahoud** [mklokocka/seminator#7]
When the input automaton reaches an accepting [inherently terminal](https://spot.lrde.epita.fr/ipynb/decompose.html) SCC, it always accepts.

When it reaches a deterministic bottom SCC, it always behaves deterministically so there is no need to stay in the 1st component. This can be even extended to SCCs that have only deterministic SCCs as successors. We could use the cut-determinism check (the cut computation, to be exact) for detecting this.

- [x] Extension to SCC without nondetereministic successor (32c5d96)
- [x] Add to ltlcross tests
- [x] Use TGBA as output if possible
- [x] Avoid multiple computation of semidet-SCCs (7c4ce4e)
- [x] Rename to `--reuse-deterministic-tails`

**Comment by xblahoud** [comment]
[bSCC.pdf](https://github.com/mklokocka/seminator/files/3084716/bSCC.pdf)

**Comment by xblahoud** [comment]
For deterministic BSCC this is implemented by fc06b6aad9ef2b470e016714c9261c3a08b9046a. 

I believe this should be extended to SCCs that could be in the deterministic part anyway. But this has to be treated carefully as such modification would interact with the SCC-aware optimization. With this optimization left unchanged, we could never reached some SCCs.

3 -> 2 -> 0    
        2 ->1

With the SCC-graph as above, if 0,1,2 are deterministic, we can create cut-edges to 2, but due to SCC-aware optimiation never reach 0 and 1 if 2 is not in the 1st component.

**Comment by xblahoud** [comment]
It would be beneficial to produce TGBA and plug the automaton unchanged in cases where we can reuse such parts. 

If Büchi automaton is requested, Spot would degeneralize it more efficient anyway.

**Comment by xblahoud** [comment]
The information which SCCs are semi-deterministic is computed over and over again. Cache it.

**Comment by xblahoud** [comment]
The enhanced version, where we reuse the whole deterministic parts as they are was implemented as `-reuse-good-SCC`. It should be renamed to `--reuse-deterministic-tails`

**Comment by adl** [comment]
The remaining issue is the same as #18 so this can be closed?

**Comment by xblahoud** [comment]
Yes, it can.
